#!/usr/bin/env bash
# Bundle the web app (../web) into native/www and point it at your API.
#
#   API_BASE=https://your-app.fly.dev ./sync-web.sh
#
# If API_BASE is empty the app will call its own origin — fine only when the
# native shell loads the site remotely, not when assets are bundled. For a real
# native build, set API_BASE to your deployed server.
set -euo pipefail
cd "$(dirname "$0")"

API_BASE="${API_BASE:-}"

rm -rf www
mkdir -p www
cp -R ../web/. www/

# Overwrite the bundled config with the chosen API base.
cat > www/config.js <<EOF
// Generated by sync-web.sh — points the bundled app at the deployed API.
window.APP_CONFIG = { apiBase: "${API_BASE}" };
EOF

if [ -z "${API_BASE}" ]; then
  echo "⚠  API_BASE is empty — set it to your deployed URL before a device build,"
  echo "   e.g. API_BASE=https://your-app.fly.dev ./sync-web.sh"
fi
echo "✅ Bundled ../web into native/www (apiBase='${API_BASE}')"
